### ISSUE TITLE
Animals Despawning/Graves

### ISSUE THREAD

**Issue by Im-Death** [RichPrune/Chocolate-Edition#1]
I have found that when you leave the chunk, animals despawn. They even despawn if they are name tagged. This makes it completely inconvenient to use, making you completely dependent on the mobs spawning in the wild.

 In addition to this, the grave system that uses enigmatic legacy has cause more harm to player than anything. More often than not, when returning to claim the grave, it not only takes time to claim the grave, you often die again before you get your items, causing the previous grave to disappear. This in turn now puts the items on despawn count-down.

**Comment by RichPrune** [comment]
They shouldnt despawn if they are named, tamed, fed, or bred. I am unable to replicate them despawning with a name tag on. I wrote this in the mechanics added section under the agriculture wiki

also what eniglegacy grave system? There's a quark oddities totem of holding that spawns when you die, but not a eniglegacy one. The totem despawning can be configured in the quark config "oddities" section, by clicking on "totem of holding" and setting it so it doesn't drop items after one death.

**Comment by Im-Death** [comment]
My apologies, the animal despawning was happening on a server, so it could very well be a server problem, but it has also happened in single-player as well for me.

I also immediately assumed the eniglegacy grave system because in earlier versions it had an identical attribute. My apologies for assuming the incorrect mod.
